### ISSUE TITLE
Remove embedded HelmReleaseSpec from ApplicationGroup's application spec object

### ISSUE THREAD

**Issue by nitishm** [Azure/orkestra#143]
Each Application in the `ApplicationGroup.Spec.Applications` specifies params to be passed to the workflow generated `HelmRelease` objects using an embedded/in-line `HelmReleaseSpec` from the flux helm-controller go package.

Since Orkestra does not offer all the features of HelmRelease out-of-the-box we want to abstract these fields away into native fields and remove the inline `HelmReleaseSpec` field from the `ApplicationSpec`.

This would involve changes to the `ApplicationSpec` https://github.com/Azure/Orkestra/blob/main/api/v1alpha1/appgroup_types.go#L42, which would require changes to the code in https://github.com/Azure/Orkestra/blob/main/pkg/workflow/argo.go wherein the `HelmRelease` objects are generated.

NOTE: Any changes to the API structs (`api/xxx_types.go` file) requires the following steps to regenerate and update the CRD manifests,

 ```terminal
make generate
make manifests
```

**Comment by nitishm** [comment]
Along the lines of 
```go
type ApplicationSpec struct {
	// Subcharts provides the dependency order among the subcharts of the application
	Subcharts []DAG `json:"subcharts,omitempty"`
	// Repo is the repository configuration
	Repo registry.RepoInfo `json:"repo,omitempty"`
	// RepoPath provides the subdir path to the actual chart artifact within a Helm Registry
	// Artifactory for instance utilizes folders to store charts
	// TODO (nitishm) Move into registry.RepoInfo
	RepoPath string `json:"repoPath,omitempty"`
	// Inline HelmReleaseSpec from the flux h`elm-operator package
	// DEPRECATED
	// helmopv1.HelmReleaseSpec `json:",inline"`
	Release ReleaseConfig
}

type ReleaseConfig struct {
	Name            string
	TargetNamespace string
	Timeout         int64
	Wait            bool
	ForceUpgrade    bool
	Values          map[string]interface{}
}
```

**Comment by nitishm** [comment]
@davutkarabay this is a good issue for you to get your hands dirty. Requires changes throughout the codebase, which will give you an opportunity to touch all the logic. LMK if I should assign this to you

**Comment by nitishm** [comment]
@jonathan-innis this is good task to get familiar with the code base and see how we interact with the `HelmRelease` objects. This will help understand what is needed when you move to helm-controller's custom resource generation (like `HelmRelease` and `HelmRepository`) and any additional fields that might be needed to support the remediation features that helm-controller provides over helm-operator

**Comment by jonathan-innis** [comment]
@nitishm The following spec is what is produced if we try to integrate the spec based on what is used in the controller
```
namespace: orkestra
repo: 
  url: https://www.getambassador.io/helm 
  name: datawire
groupID: "bookinfo"
subcharts: []
release:
  chart:
    repository: "https://www.getambassador.io"
    name: ambassador 
    version: 6.6.0
  forceUpgrade: true
  targetNamespace: ambassador 
overlays:
  service:
    type: ClusterIP
```
Can you help me understand the two different fields `spec.url` and `spec.release.chart.repository`. From my perspective these two fields look redundant?

**Comment by nitishm** [comment]
Yup you are right they became redundant after adding the `RepoInfo` field to the API. I quite like the alternative with one comment. We change `authRef` to `repoSecretRef`, `helmSecretRef` or `helmRepoSecretRef` to make it more descriptive and obvious. 

Also, as we get rid of the in-line `HelmReleaseSpec` we can switch the name `overlays` back to `values`.

**Comment by jonathan-innis** [comment]
I see, so proposed api spec would then be
```
groupID: "bookinfo"
subcharts: []
chart:
  repository: "https://www.getambassador.io"
  name: ambassador
  version: 6.6.0
  helmRepoSecretRef:
    name: example
    namespace: example
  forceUpgrade: true
  targetNamespace: ambassador
values:
  service:
     type: ClusterIP
```
