### ISSUE TITLE
Display Application and ApplicationGroup reconciliation status through a list of transition states

### ISSUE THREAD

**Issue by nitishm** [Azure/orkestra#146]
It would be nice to capture the status as a **list of transition states** similar to how it is done in helm-controller's `HelmRelease` object status.

For example https://toolkit.fluxcd.io/components/source/helmrepositories/#status-examples
```yaml
status:
  url: http://<host>/helmrepository/default/stable/index.yaml
  conditions:
    - lastTransitionTime: "2020-04-10T09:34:45Z"
      message: Helm repository index is available at /data/helmrepository/default/stable/index-21c195d78e699e4b656e2885887d019627838993.yaml
      reason: IndexationSucceeded
      status: "True"
      type: Ready
```
> This needs some scoping

**Comment by jonathan-innis** [comment]
Picking this one up

**Comment by jonathan-innis** [comment]
@nitishm  Can you explain what you mean by "This needs some scoping"?

**Comment by nitishm** [comment]
We can remove the label. This should be good to start working on.

**Comment by jonathan-innis** [comment]
Here's the proposed api spec:

```yaml
status:
  applications:
    - status:
        url: http://<host>/helmrepository/default/stable/index.yaml
        conditions: <status conditions from the underlying helmRelease object>
  conditions:
    - lastTransitionTime: "2020-04-10T09:34:45Z"
       message: <message>
       reason: ReconciliationSucceeded
       status: "True"
       type: Deploy
    - lastTransitionTime: "2020-04-10T09:34:45Z"
       message: <message>
       reason: WorkflowSucceeded
       status: "True"
       type: Ready
```

Does this capture the intention? Having two conditions at the top level, essentially `Deploy` and `Ready` type would separate out the ability to reconcile the spec and the provisioning and state of the workflow itself
