### ISSUE TITLE
Orkestra deployment's staging repo url should use the release name and namespace

### ISSUE THREAD

**Issue by nitishm** [Azure/orkestra#159]
See https://github.com/Azure/orkestra/blob/main/chart/orkestra/templates/deployment.yaml#L34-L36
```yaml
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args: 
          - --staging-repo-url
          - http://orkestra-chartmuseum.orkestra:8080 
```

Switch the following
```yaml
          - --staging-repo-url
          - http://orkestra-chartmuseum.orkestra:8080 
```
with,
```yaml
          - --staging-repo-url
          - http://{{ .Release.Name }}-chartmuseum.{{ .Release.Namespace }}:8080 
```
