### ISSUE TITLE
Orkestra should use the ApplicationGroup namespace as the namespace for Argo workflows

### ISSUE THREAD

**Issue by jonathan-innis** [Azure/orkestra#231]
**Is your feature request related to a problem? Please describe.**
Currently, we use always use the `orkestra` namespace to run the argo workflows. Instead of using this always, we should use the `ApplicaitonGroup` namespace and generate the workflows in that namespace. This will allow teams that have security models that separate their logic into different namespaces to use multiple application groups in different namespaces.

**Comment by jonathan-innis** [comment]
This will cause us to create a service account and assign this service account the ClusterRole binding that allows the executor to do any of the actions that it needs to do to provision the resources

**Comment by nitishm** [comment]
@jonathan-innis Can we close this as a "will not fix" ?

**Comment by jonathan-innis** [comment]
This one wasn't the "won't fix" one, I think we said we might take this at a later date

**Comment by nitishm** [comment]
oops

**Comment by jonathan-innis** [comment]
Also, these workflows not being in separate namespaces prevents us from parallelizing the tests which will be critical as the full reconciliation loop takes quite a while if we run these in serial

**Comment by nitishm** [comment]
So, we do have an `env` variable for specifying the workflow namespace `WORKFLOW_NAMESPACE` 
 being set through the `values.yaml` in the `deployment.yaml`
 ```yaml
          env:
          - name: WORKFLOW_NAMESPACE 
            value: {{ .Release.Namespace }} 
          - name: WORKFLOW_SERVICEACCOUNT_NAME 
            value: {{ include "orkestra.serviceAccountName" . }} 
```
Can you give this a try since I haven't really tried it outside of the `orkestra` namespace. I am guessing the `ServiceAccount`s are going to be an issue that must be addressed in a different namespace.
