### ISSUE TITLE
Add plugins field to ApplicationSpec

### ISSUE THREAD

**Issue by nitishm** [Azure/orkestra#365]
Add plugins field to ApplicationSpec

```yaml
spec:
  interval: 1m
  applications:
    - name: ambassador
      dependencies: []
      spec:
        chart:
          url: "https://www.getambassador.io/helm"
          name: ambassador 
          version: 6.6.0
        release:
          targetNamespace: ambassador 
          values:
            service:
              type: ClusterIP
      plugin:
      - name: quality-gates
        type: keptn
        # specify dependencies on other plugin executors
        # eg. keptn depends on default executor to complete before
        # running the tests
        dependencies: ["default"]
        configMapRef: 
          name: keptn-config
          namespace: keptn
```
sample configuration 
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: keptn-config
  namespace: keptn
data:
  shipyard.yaml: |
    apiVersion: "spec.keptn.sh/0.2.0"
    kind: "Shipyard"
    metadata:
      name: "shipyard"
    spec:
      stages:
        - name: "dev"
          sequences:
            - name: "delivery"
              tasks:
                - name: "deployment"
                  properties:
                    # "direct" -> helm service 
                    deploymentstrategy: "direct"
                - name: "release"
        - name: "production"
          sequences:
            - name: "delivery"
              triggeredOn:
                - event: "dev.delivery.finished"
              tasks: 
              - name: "deployment"
                deploymentstrategy: "direct"
              - name: "release"
  slo.yaml: |
    stage: dev
    data:
      spec_version: '0.1.0'
      comparison:
        compare_with: "single_result"
        include_result_with_score: "pass"
        aggregate_function: avg
      objectives:
        - sli: http_response_time_seconds_main_page_sum
          pass:
            - criteria:
                - "<=1"
          warning:
            - criteria:
                - "<=0.5"
        - sli: request_throughput
          pass:
            - criteria:
                - "<=+100%"
                - ">=-80%"
        - sli: go_routines
          pass:
            - criteria:
                - "<=100"
      total_score:
        pass: "90%"
        warning: "75%"
  sli.yaml: |
    stage: dev
    data:
      spec_version: '1.0'
      indicators:
        http_response_time_seconds_main_page_sum: sum(rate(http_server_request_duration_seconds_sum{method="GET",route="/",status_code="200",job="$SERVICE-$PROJECT-$STAGE-canary"}[$DURATION_SECONDS])/rate(http_server_request_duration_seconds_count{method="GET",route="/",status_code="200",job="$SERVICE-$PROJECT-$STAGE-canary"}[$DURATION_SECONDS]))
        http_requests_total_sucess: http_requests_total{status="success"}
        go_routines: go_goroutines{job="$SERVICE-$PROJECT-$STAGE"}
        request_throughput: sum(rate(http_requests_total{status="success"}[$DURATION_SECONDS]))
```
