### ISSUE TITLE
Support running one or more workflow executors as part of the Application workflow node execution template

### ISSUE THREAD

**Issue by nitishm** [Azure/orkestra#379]
**Is your feature request related to a problem? Please describe.**
Support running one or more workflow executors as part of the Application workflow node execution template

**Describe the solution you'd like**
New fields that support configuring the Workflow configurations would be of the format 
```yaml
apiVersion: orkestra.azure.microsoft.com/v1alpha1
kind: ApplicationGroup
metadata:
  name: bookinfo 
spec:
  applications:
    - name: bookinfo 
      dependencies: [ambassador]
      spec:
        chart:
          url: "https://nitishm.github.io/charts"
          name: bookinfo 
          version: v1
        release:
          targetNamespace: bookinfo 
          values:
            productpage:
              replicaCount: 1
            details:
              replicaCount: 1
            reviews:
              replicaCount: 1
            ratings:
              replicaCount: 1
        workflow:
          - name: helmrelease
            dependencies: []
            # image: azureorkestra/executor:v0.4.2
            type: helmrelease
            params: nil
          - name: keptn
            type: helmrelease
            dependencies: ["helmrelease"]
            # image: azureorkestra/keptn-executor:v0.1.0
            type: keptn
            params:
              configmapRef: 
                name: keptn-config
                namespace: orkestra
          - name: my-custom-executor
            type: custom
            dependencies: ["helmrelease"]
            image: azureorkestra/my-custom-executor:v0.1.0
            params:
              foo: 
                bar: value
                baz: value
```

These fields should in return be used to generate the executor template DAG for the workflow executor associated with the application workflow node.

**Describe alternatives you've considered**

**Additional context**
